sudo: required

language: node_js

services:
  - docker

node_js:
  - "8"

cache: yarn

script:
  - docker build -t selfz .

before_deploy:
  - docker login -u="nvlih" -p="chunchun19"
  - docker tag selfz nvlih/selfz:latest
  - docker image ls
deploy:
  - provider: script
    skip_cleanup: true
    on:
      all_branches: true
    script:
      docker push nvlih/selfz:latest